// Re-export all icons from lucide-react organized by category
import {
  Activity,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  Anchor,
  Archive,
  ArrowBigDown,
  ArrowBigLeft,
  ArrowBigRight,
  ArrowBigUp,
  ArrowDown,
  ArrowDownCircle,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowLeft,
  ArrowLeftCircle,
  ArrowRight,
  ArrowRightCircle,
  ArrowUp,
  ArrowUpCircle,
  ArrowUpLeft,
  ArrowUpRight,
  AtSign,
  Award,
  Backpack,
  Badge,
  BaggageClaim,
  Ban,
  Banana,
  BanknoteIcon as Bank,
  BarChart,
  BarChart2,
  BarChart3,
  BarChart4,
  Battery,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  BatteryWarning,
  Bell,
  BellDot,
  BellMinus,
  BellOff,
  BellPlus,
  BellRing,
  Bike,
  Binary,
  Bitcoin,
  Bluetooth,
  BluetoothConnected,
  BluetoothOff,
  BluetoothSearching,
  Bold,
  Book,
  BookOpen,
  Bookmark,
  BookmarkMinus,
  BookmarkPlus,
  Bot,
  Box,
  BoxSelect,
  Briefcase,
  Bug,
  Building,
  Building2,
  Bus,
  PieChart,
  LineChart,
  BarChartHorizontal,
  TrendingUp,
  TrendingDown,
  Mail,
  MessageCircle,
  MessageSquare,
  Phone,
  PhoneCall,
  PhoneForwarded,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  PhoneOutgoing,
  Share,
  Share2,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  UserX,
  Users,
  Group,
  BadgeAlertIcon as AlertIcon,
  BellIcon as NotificationBell,
  CheckCircle,
  Info,
  X,
  XCircle,
  XOctagon,
  Circle,
  Square,
  Triangle,
  Hexagon,
  Octagon,
  Pentagon,
  Code,
  CodepenIcon,
  Database,
  File,
  FileCode,
  FileText,
  FolderIcon,
  GitGraphIcon as Git,
  GitGraphIcon as Git,
  Terminal,
  FileIcon,
  FileArchive,
  FileAudio,
  FileCheck,
  FileCode2,
  FileCog,
  FileImage,
  FileLock,
  FileQuestion,
  FileSearch,
  FileSpreadsheet,
  FileTextIcon as FileText2,
  FileVideo,
  FileWarning,
  FileX,
  Image,
  Images,
  Camera,
  Video,
  Film,
  PictureInPictureIcon as Picture,
  Clock,
  Calendar,
  Timer,
  Hourglass,
  Watch,
  Cloud,
  CloudDrizzle,
  CloudFog,
  CloudLightning,
  CloudRain,
  CloudSnow,
  Cloudy,
  Sun,
  Sunrise,
  Sunset,
  Wind,
  Map,
  MapPin,
  Navigation,
  Navigation2,
  Compass,
  CreditCard,
  DollarSign,
  Euro,
  Percent,
  ShoppingBag,
  ShoppingCart,
  BookIcon as EducationBook,
  GraduationCap,
  School,
  Library,
  Lock,
  Unlock,
  Shield,
  Key,
  Fingerprint,
  BoldIcon as BoldText,
  Italic,
  Underline,
  List,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Tv,
  Smartphone,
  Tablet,
  Laptop,
  ComputerIcon as Desktop,
  Printer,
  Speaker,
  Headphones,
  LayoutIcon,
  Columns,
  Grid,
  Rows,
  Table,
} from "lucide-react"

// Export organized by category
export const Icons = {
  general: {
    activity: Activity,
    alertCircle: AlertCircle,
    // ... other general icons
  },
  charts: {
    pieChart: PieChart,
    lineChart: LineChart,
    barChartHorizontal: BarChartHorizontal,
    trendingUp: TrendingUp,
    trendingDown: TrendingDown,
  },
  communication: {
    mail: Mail,
    messageCircle: MessageCircle,
    messageSquare: MessageSquare,
    phone: Phone,
    // ... other communication icons
  },
  users: {
    user: User,
    userCheck: UserCheck,
    userMinus: UserMinus,
    userPlus: UserPlus,
    userX: UserX,
    users: Users,
    group: Group,
  },
  alerts: {
    alert: AlertIcon,
    notification: NotificationBell,
    checkCircle: CheckCircle,
    info: Info,
    x: X,
    xCircle: XCircle,
    xOctagon: XOctagon,
  },
  shapes: {
    circle: Circle,
    square: Square,
    triangle: Triangle,
    hexagon: Hexagon,
    octagon: Octagon,
    pentagon: Pentagon,
  },
  development: {
    code: Code,
    codepen: CodepenIcon,
    database: Database,
    file: File,
    fileCode: FileCode,
    fileText: FileText,
    folder: FolderIcon,
    git: Git,
    github: Github,
    terminal: Terminal,
  },
  files: {
    file: FileIcon,
    archive: FileArchive,
    audio: FileAudio,
    check: FileCheck,
    code: FileCode2,
    cog: FileCog,
    image: FileImage,
    lock: FileLock,
    question: FileQuestion,
    search: FileSearch,
    spreadsheet: FileSpreadsheet,
    text: FileText2,
    video: FileVideo,
    warning: FileWarning,
    x: FileX,
  },
  images: {
    image: Image,
    images: Images,
    camera: Camera,
    video: Video,
    film: Film,
    picture: Picture,
  },
  time: {
    clock: Clock,
    calendar: Calendar,
    timer: Timer,
    hourglass: Hourglass,
    watch: Watch,
  },
  weather: {
    cloud: Cloud,
    drizzle: CloudDrizzle,
    fog: CloudFog,
    lightning: CloudLightning,
    rain: CloudRain,
    snow: CloudSnow,
    cloudy: Cloudy,
    sun: Sun,
    sunrise: Sunrise,
    sunset: Sunset,
    wind: Wind,
  },
  mapsAndTravel: {
    map: Map,
    mapPin: MapPin,
    navigation: Navigation,
    navigation2: Navigation2,
    compass: Compass,
  },
  finance: {
    creditCard: CreditCard,
    dollarSign: DollarSign,
    euro: Euro,
    percent: Percent,
    shoppingBag: ShoppingBag,
    shoppingCart: ShoppingCart,
  },
  education: {
    book: EducationBook,
    graduationCap: GraduationCap,
    school: School,
    library: Library,
  },
  security: {
    lock: Lock,
    unlock: Unlock,
    shield: Shield,
    key: Key,
    fingerprint: Fingerprint,
  },
  editor: {
    bold: BoldText,
    italic: Italic,
    underline: Underline,
    list: List,
    alignLeft: AlignLeft,
    alignCenter: AlignCenter,
    alignRight: AlignRight,
    alignJustify: AlignJustify,
  },
  mediaAndDevices: {
    tv: Tv,
    smartphone: Smartphone,
    tablet: Tablet,
    laptop: Laptop,
    desktop: Desktop,
    printer: Printer,
    speaker: Speaker,
    headphones: Headphones,
  },
  layout: {
    layout: LayoutIcon,
    columns: Columns,
    grid: Grid,
    rows: Rows,
    table: Table,
  },
}

export default Icons

